Repository nav7FSC/FitTrendz_E-Commerce, pull requests merged in 2025-03, with the labels that each got.

#68 Layout done, but need to implement more functionality
  my-app/package-lock.json
  my-app/package.json
  my-app/src/App.jsx
  my-app/src/Recommended/Recommended.css
  my-app/src/Recommended/Recommended.jsx
  my-app/src/Sidebar/Category/Category.css
  my-app/src/Sidebar/Category/Category.jsx
  my-app/src/Sidebar/Colors/Colors.css
  my-app/src/Sidebar/Colors/Colors.jsx
  my-app/src/Sidebar/Price/Price.css
  my-app/src/Sidebar/Price/Price.jsx
  my-app/src/Sidebar/Sidebar.css
  my-app/src/Sidebar/Sidebar.jsx
  my-app/src/components/Navbar.css
  my-app/src/components/Navbar.jsx
  my-app/src/components/button.jsx
  my-app/src/components/card.jsx
  my-app/src/components/input.jsx
  my-app/src/db/data.jsx
  my-app/src/pages/catalog.jsx
  my-app/src/pages/pageStyling.css
  my-app/src/products/products.css
  my-app/src/products/products.jsx
Labels: enhancement

#69 Functionality Done. Few visual glitches
  my-app/src/Recommended/Recommended.jsx
  my-app/src/Sidebar/Category/Category.jsx
  my-app/src/Sidebar/Colors/Colors.jsx
  my-app/src/Sidebar/Price/Price.jsx
  my-app/src/Sidebar/Sidebar.css
  my-app/src/Sidebar/Sidebar.jsx
  my-app/src/components/button.jsx
  my-app/src/components/card.jsx
  my-app/src/components/input.jsx
  my-app/src/db/data.jsx
  my-app/src/index.css
  my-app/src/pages/catalog.jsx
  my-app/src/products/products.jsx
Labels: enhancement

#71 Checkout Page
  my-app/src/pages/check-out.jsx
  my-app/src/pages/pageStyling.css
Labels: enhancement, feature

#72 Cart page
  my-app/src/App.jsx
  my-app/src/components/Navbar.jsx
  my-app/src/pages/cart.jsx
  my-app/src/pages/pageStyling.css
Labels: enhancement

#74 Created the UserManagement page
  my-app/src/App.jsx
  my-app/src/components/Navbar.jsx
  my-app/src/pages/UserManagement.jsx
  node_modules/.package-lock.json
  package-lock.json
Labels: enhancement, feature

#76 I created a wishlist page and I fixe the gmail login button
  my-app/src/App.jsx
  my-app/src/components/Navbar.css
  my-app/src/components/Navbar.jsx
  my-app/src/pages/pageStyling.css
  my-app/src/pages/sign-in.jsx
  my-app/src/pages/wishlist.jsx
Labels: enhancement, feature

#79 Updated read me file -Nav
  README.md
Labels: documentation, enhancement

#80 Reduced navbar height -NAV
  my-app/src/components/Navbar.css
Labels: enhancement, fixed
