Repository nav7FSC/FitTrendz_E-Commerce, pull requests merged in 2025-04, with the labels that each got.

#85 Sprint 3 Burndown Chart
  Documentation/Burndown_Charts/Sprint 3 – FitTrendz E-Commerce Board – YouTrack Agile Board.pdf
Labels: documentation

#89 Updated the about.jsx page
  my-app/src/pages/about.jsx
Labels: documentation, enhancement

#90 Added a new Size Quiz page
  my-app/src/App.jsx
  my-app/src/components/Navbar.jsx
  my-app/src/pages/quiz.jsx
Labels: enhancement, feature

#97 Login error message when 401 returned from backend
  my-app/src/pages/pageStyling.css
  my-app/src/pages/sign-in.jsx
Labels: bug

#98 Add Order History Page and Cart Item Count Badge
  my-app/package-lock.json
  my-app/src/App.jsx
  my-app/src/components/AuthContext.jsx
  my-app/src/components/Navbar.jsx
  my-app/src/pages/OrderHistory.jsx
  my-app/src/pages/cart.jsx
  my-app/src/pages/pageStyling.css
  my-app/src/pages/sign-in.jsx
Labels: enhancement, feature
