Repository nav7FSC/FitTrendz_E-Commerce, pull requests merged in 2025-02, with the labels that each got.

#2 Added documentation for team member contact information and meeting t…
  Documentation/TEAM CONTACT LIST and MEETING TIMES PDF.pdf
Labels: documentation

#10 The Problem Statement & Description
  Documentation/The Problem Statement & Description.pdf
Labels: documentation

#12 Created a new README file - Nav Singh
  README.md
Labels: documentation

#13 Problem Statement & Description File Version - Nav Singh
  Documentation/File: The Problem Statement & Description
  Documentation/PDF: The Problem Statement & Description.pdf
Labels: documentation, enhancement

#18 burndown chart from YouTrack
  Documentation/Burndown_Charts/FitTrendz E-Commerce Board - Burndown Chart -Sprint 1.pdf
Labels: documentation

#19 Submitted initial project proposal - Nav Singh
  Documentation/Project Proposal.pdf
Labels: documentation

#20 Project Backlog: Features, Stories, Security - Nav Singh
  Documentation/Project Backlog.pdf
Labels: documentation

#21 Updated README.md
  README.md
Labels: enhancement

#23 file structure - remove .gitkeep file when you add something to the file
  src/assets/.gitkeep
  src/components/.gitkeep
  src/context/form/.gitkeep
  src/context/ui/.gitkeep
  src/data/.gitkeep
  src/hooks/.gitkeep
  src/pages/home/.gitkeep
  src/pages/login/.gitkeep
  src/pages/signup/.gitkeep
  src/utils/.gitkeep
Labels: fixed

#48 Added React Modules
  .gitignore
  .idea/.gitignore
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  Documentation/FitTrendz E-Commerce Board - Burndown Chart -Sprint 1.pdf
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: bug, fixed

#51 Added React files
  my-app/.gitignore
  my-app/README.md
  my-app/eslint.config.js
  my-app/index.html
  my-app/package-lock.json
  my-app/package.json
  my-app/public/vite.svg
  my-app/src/App.css
  my-app/src/App.jsx
  my-app/src/assets/react.svg
  my-app/src/index.css
  my-app/src/main.jsx
  my-app/vite.config.js
  src/assets/.gitkeep
  src/components/.gitkeep
  src/context/form/.gitkeep
  src/context/ui/.gitkeep
  src/data/.gitkeep
  src/hooks/.gitkeep
  src/pages/home/.gitkeep
  src/pages/login/.gitkeep
  src/pages/signup/.gitkeep
  src/utils/.gitkeep
Labels: bug, fixed

#55 24 signup page
  my-app/src/App.jsx
  my-app/src/components/Navbar.jsx
  my-app/src/pages/Home.css
  my-app/src/pages/Signup-page.css
  my-app/src/pages/google-icon.png
  my-app/src/pages/signup-page.jsx
Labels: enhancement, feature

#57 Created sign in page
  my-app/src/App.jsx
  my-app/src/pages/sign-in.css
  my-app/src/pages/sign-in.jsx
  my-app/src/pages/signup-page.jsx
Labels: enhancement, feature

#62 Added real-time input validation with dynamic styling. Input fields now show a red or green outline and background based on validation status.
  my-app/package-lock.json
  my-app/package.json
  my-app/src/pages/Signup-page.css
  my-app/src/pages/signup-page.jsx
Labels: enhancement

#61 Changes to be committed:
  Documentation/Burndown_Charts/Sprint 1 – FitTrendz E-Commerce Board - Burndown Chart.pdf
  Documentation/Burndown_Charts/Sprint 2 – FitTrendz E-Commerce Board – YouTrack Agile Board1.pdf
Labels: documentation
